### ISSUE TITLE
Streaming example from docs doesnt work

### ISSUE THREAD

**Issue by ludwikbukowski** [mgallo/openai.ex#42] opened 2023-06-04 18:47 UTC
### Describe the feature or improvement you're requesting

Not sure if doing something wrong but generally the example from docs:
``` elixir
OpenAI.chat_completion([
    model: "gpt-3.5-turbo",
    messages: [
      %{role: "system", content: "You are a helpful assistant."},
      %{role: "user", content: "Who won the world series in 2020?"},
      %{role: "assistant", content: "The Los Angeles Dodgers won the World Series in 2020."},
      %{role: "user", content: "Where was it played?"}
    ],
    stream: true, # set this param to true
  ]
)
|> Stream.each(fn res ->
  IO.inspect(res)
end)
|> Stream.run()
```

generates an error:
```elixir
** (CaseClauseError) no case clause matching: {:ok, %HTTPoison.AsyncResponse{id: #Reference<0.2742941706.3081240585.23996>}}
    (openai 0.5.1) lib/openai/client.ex:26: OpenAI.Client.handle_response/1
```

**Comment by mgallo** [comment] 2023-06-07 20:05
@ludwikbukowski Hi! Sorry for the late response, the streaming API relies on HTTPoison streams and you should set in the `http_options` the following params: `[recv_timeout: :infinity, stream_to: self(), async: :once]`, as described in [this line of the readme](https://github.com/mgallo/openai.ex/blob/main/README.md?plain=1#L274) (probably is not so clear, and I should highlight it better 😓, sorry), basically you have to declare where you want to stream the response.

You can set the `http_options `in your main configuration in `config.exs`, but probably, if you're using the library also to do other calls, is better to pass a specific config to this specific function, like this:

```elixir
# this will take all the params from your main config, except the http_options that will be overriden
streaming_config = %OpenAI.Config{
  http_options: [recv_timeout: :infinity, stream_to: self(), async: :once]
}

OpenAI.chat_completion([
  model: "gpt-3.5-turbo",
  messages: [
    %{role: "system", content: "You are a helpful assistant."},
    %{role: "user", content: "Who won the world series in 2020?"},
    %{role: "assistant", content: "The Los Angeles Dodgers won the World Series in 2020."},
    %{role: "user", content: "Where was it played?"}
  ],
  stream: true,
],
streaming_config # <---- pass the streaming_config here!
)
|> Stream.each(fn res ->
  IO.inspect(res)
  end)
  |> Stream.run()
```

other references:
- [stream API PR](https://github.com/mgallo/openai.ex/pull/36)
- [config override documentation](https://github.com/mgallo/openai.ex#configuration-override)

this should solve your issue, let me know if it works so we can close this thread, thanks 👍

**Comment by mgallo** [comment] 2023-06-18 14:30
I am closing this PR for now because the problem cannot be reproduced, and a possible solution was provided,

**Closed by mgallo** 2023-06-18 14:30 UTC
